name: Update Auto-Checkin Cron

on:
  schedule:
    - cron: '0 21 * * *'  # UTC 21:00 = 北京时间 05:00
  workflow_dispatch:

jobs:
  update-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout updater repo
        uses: actions/checkout@v3

      - name: Clone target repo
        run: git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/<你的用户名>/auto-checkin.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run update script
        run: python update_cron.py
