name: Update Auto-Checkin Cron

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 5:00 AM 北京时间，UTC 21:00
  workflow_dispatch:

jobs:
  update-cron:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保写权限

    steps:
      - name: Checkout scheduler repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv  # 安装 python-dotenv

      - name: Run update script
        env:
          TOKEN: ${{ secrets.TOKEN }}  # 将 GitHub Token 放入 Secrets
        run: python update_cron.py
